import type { Metadata } from "next";
import { Inter, Roboto_Mono, Quicksand } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import { ThemeProvider } from "../components/ThemeProvider";
import NavVertical from "../components/Nav";

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Musica-Music-Streaming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto_mono.variable} ${quicksand.variable}`}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className="bg-white dark:bg-[#1D2123] p-4 md:p-8 flex font-quicksand">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* Vertical Nav-Bar */}
          <div className="hidden md:block">
            <NavVertical />
          </div>
          {/* Main Body */}
          <div className="flex flex-col flex-1">
            <div className="bg-white dark:bg-[#1D2123] h-[100px] w-[100%] fixed top-0 left-0 z-20 mx-auto drop-shadow-lg"></div>
            <Header />
            <div>{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
